base_url = "http://80.188.223.202:35506/v1"
api_key = "905ce35225b6dcb083fc93a661860aed6bfda5ffc8d6ae256e2d7a7055263db3"
temperature = 0.7
top_p = 0.8
top_k = 20
min_p = 0
repetition_penalty = 1.5
length_penalty = 3.0
max_tokens = 200
